djangobook/mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from mysite.views import *
from books.views import *
from cookies.views import *
from contact.views import *

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^meta/$', display_meta),
    url(r'^time/$', current_datetime),
    url(r'^time/plus/(\d{1,2})/$', hours_ahead),
#    url(r'^search-form/$', search_form),
    url(r'^search/$', search),
    url(r'^contact/thanks/$', 'contact.views.thanks'),
    url(r'^contact/$', contact),
    url(r'^cookie/$', show_color),
    url(r'^set_cookie/$', set_color),
)

#if settings.DEBUG:
#    urlpatterns += patterns('',
#        (r'^debuginfo/$', 'mysite.views.debug'),
#    )

djangobook/mysite/books/models.py
from django.db import models

# Create your models here.
class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    def __str__(self):
	return self.name

class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField('e-mail', blank=True)

    def __str__(self):
	return u'%s %s' % (self.first_name, self.last_name)
	
class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField()

    def __str__(self):
	return self.title

djangobook/mysite/contact/models.py
from django.db import models

# Create your models here.

djangobook/mysite/cookies/models.py
from django.db import models

# Create your models here.

djangobook/mysite/contact/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False, label='Your e-mail address')
    message = forms.CharField(widget=forms.Textarea)

    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words!")
        return message

djangobook/mysite/books/views.py
from django.http import HttpResponse
from django.shortcuts import render_to_response, render
from books.models import Book

#def search(request):
#    error = False
#    if 'q' in request.GET and request.GET['q']:
#        q = request.GET['q']
#        books = Book.objects.filter(title__icontains=q)
#        return render_to_response('search_results.html',
#            {'books': books, 'query': q})
#    else:
#        #return HttpResponse('Please submit a search term.')
#        return render(request, 'search_form.html', {'error': True})
#def search_form(request):
#    return render_to_response('search_form.html')

def search(request):
    errors = []
    if 'q' in request.GET:
        q = request.GET['q']
        if not q:
            errors.append('Enter a search term.')
	elif len(q) > 20:
            errors.append('Please enter at most 20 characters.')
        else:
            books = Book.objects.filter(title__icontains=q)
            return render_to_response('search_results.html',{'books': books, 'query': q})
    #return render_to_response('search_form.html',{'error': error})
    return render(request, 'search_form.html', {'errors': errors})

djangobook/mysite/contact/views.py
from django.shortcuts import render_to_response, render
from contact.forms import ContactForm
from django.core.mail import send_mail

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'noreply@example.com'),
                ['823772686@qq.com'],
            )
            return HttpResponseRedirect('/contact/thanks/')
    else:
        form = ContactForm(initial={'subject': 'I love your site!'})
    #return render_to_response('contact_form.html', {'form': form})
    return render(request, 'contact_form.html', {'form': form})

def thanks(request):
    return render_to_response('contact_thanks.html')

djangobook/mysite/cookies/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def show_color(request):
    if "favorite_color" in request.COOKIES:
        return HttpResponse("Your favorite color is %s" % request.COOKIES["favorite_color"])
    else:
        return HttpResponse("You don't have a favorite color.")

def set_color(request):
    if "favorite_color" in request.GET:

        # Create an HttpResponse object...
        response = HttpResponse("Your favorite color is now %s" % request.GET["favorite_color"])

        # ... and set a cookie on the response
        response.set_cookie("favorite_color", request.GET["favorite_color"])

        return response

    else:
        return HttpResponse("You didn't give a favorite color.")

djangobook/mysite/mysite/views.py
from django.template.loader import get_template
from django.template import Context
from django.http import HttpResponse
from django.shortcuts import render_to_response, render
import datetime

def display_meta(request):
    #metas = request.META.items()
    #print request.META
    #print metas
    #metas.sort()
    #html = [] 
    #for k, v in metas:
    #    html.append('<tr><td>%s</td><td>%s</td></tr>' % (k, v))
    #return HttpResponse('<table>%s</table>' % '\n'.join(html))
    return render(request, 'display_meta.html', {'metas': request.META, 'path': request.path})
    #for k, v in request.META.items():
#	return render(request, 'display_meta.html', {'key': k,'value': v})

#def hello(request):
#    return HttpResponse("Hello world")

#def current_datetime(request):
#    now = datetime.datetime.now()
#    t = get_template('current_datetime.html')
#    html = t.render(Context({'current_date': now}))
#    return HttpResponse(html)

def current_datetime(request):
    current_date = datetime.datetime.now()
    #return render_to_response('current_datetime.html', {'current_date': current_date})
    #return render(request, 'current_datetime.html', {'current_date': current_date})
    return render(request, 'current_datetime.html', locals())

def hours_ahead(request, offset):
    try:
        hour_offset = int(offset)
    except ValueError:
        raise Http404()
    dt = datetime.datetime.now() + datetime.timedelta(hours=hour_offset)
    #html = "<html><body>In %s hour(s), it will be %s.</body></html>" % (offset, dt)
    #return HttpResponse(html)
    return render(request, 'hours_ahead.html', {'hour_offset': hour_offset, 'next_time': dt})

#def search_form(request):
#    return render_to_response('search_form.html')

#def search(request):
#    if 'q' in request.GET:
#        message = 'You searched for: %r' % request.GET['q']
#    else:
#        message = 'You submitted an empty form.'
#    return HttpResponse(message)

djangobook/mysite/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <h1>My helpful timestamp site</h1>
    {% block content %}{% endblock %}
    {% block footer %}
    <hr>
    <p>Thanks for visiting my site.</p>
    {% endblock %}
</body>
</html>

djangobook/mysite/templates/contact_form.html
<html>
<head>
    <title>Contact us</title>
</head>
<body>
    <h1>Contact us</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
	{% csrf_token %}
        <div class="field">
            {{ form.subject.errors }}
            <label for="id_subject">Subject:</label>
            {{ form.subject }}
        </div>
        <div class="field">
            {{ form.email.errors }}
            <label for="id_email">Your e-mail address:</label>
            {{ form.email }}
        </div>
        <div class="field{% if form.message.errors %} errors{% endif %}">
    	    {% if form.message.errors %}
            <ul>
            {% for error in form.message.errors %}
           	 <li><strong>{{ error }}</strong></li>
            {% endfor %}
            </ul>
    	    {% endif %}
    	    <label for="id_message">Message:</label>
    	    {{ form.message }}
	</div>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

djangobook/mysite/templates/contact_thanks.html
Thank you !

djangobook/mysite/templates/current_datetime.html
{% extends "base.html" %}

{% block title %}The current time{% endblock %}

{% block content %}
<p>It is now {{ current_date }}.</p>
{% endblock %}

djangobook/mysite/templates/display_meta.html
{% extends "base.html" %}

{% block title %}The meta info{% endblock %}

{% block content %}
<p>Welcome to the page at {{path}} . </p>
<table>
{% for k, v in metas.items %}
<tr><td>{{k}}</td><td>{{v}}</td></tr>
{% endfor %}
</table>
{% endblock %}

djangobook/mysite/templates/hours_ahead.html
{% extends "base.html" %}

{% block title %}Future time{% endblock %}

{% block content %}
<p>In {{ hour_offset }} hour(s), it will be {{ next_time }}.</p>
{% endblock %}

djangobook/mysite/templates/search_form.html
<html>
<head>
    <title>Search</title>
</head>
<body>
    {% if errors %}
	<ul>
	    {% for error in errors %}
	    <li>{{ error }}</li>
	    {% endfor %}
	</ul>
    {% endif %}
    <form action="" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
</body>
</html>

djangobook/mysite/templates/search_results.html
<p>You searched for: <strong>{{ query }}</strong></p>

{% if books %}
    <p>Found {{ books|length }} book{{ books|pluralize }}.</p>
    <ul>
        {% for book in books %}
        <li>{{ book.title }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No books matched your search criteria.</p>
{% endif %}